<a href="https://colab.research.google.com/github/ykumargupta/AbstractiveTextSummarizer/blob/master/TextSummarization9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Cleaning Dataset using Pandas and Numpy

In [ ]:
import numpy as np
import pandas as pd

import os

In [ ]:
summary=pd.read_csv('/content/drive/Shareddrives/Deep Learning/Dataset/cnn_dailymail/news_summary.csv',encoding='iso-8859-1')

In [ ]:
#summary = pd.read_csv('news_summary.csv', encoding='iso-8859-1')
raw = pd.read_csv('/content/drive/Shareddrives/Deep Learning/Dataset/cnn_dailymail/news_summary.csv', encoding='iso-8859-1')

In [ ]:
pre = pd.DataFrame()
pre['text'] = pd.concat([pre1['text'], pre2['text']], ignore_index=True)
pre['summary'] = pd.concat([pre1['headlines'],pre2['headlines']],ignore_index = True)
pre.head(5)

text  \
0  Saurav Kant, an alumnus of upGrad and IIIT-B's...   
1  Kunal Shah's credit card bill payment platform...   
2  New Zealand defeated India by 8 wickets in the...   
3  With Aegon Life iTerm Insurance plan, customer...   
4  Speaking about the sexual harassment allegatio...   

                                             summary  
0  upGrad learner switches to career in ML & Al w...  
1  Delhi techie wins free food from Swiggy for on...  
2  New Zealand end Rohit Sharma-led India's 12-ma...  
3  Aegon life iTerm insurance plan helps customer...  
4  Have known Hirani for yrs, what if MeToo claim...

In [ ]:
pre.shape

(102915, 2)

Shape of the Dataset with NULL values *(102915, 2)*

In [ ]:
pre.text.describe()

count                                                102797
unique                                               102756
top       The first wicket and first catch in Test crick...
freq                                                      2
Name: text, dtype: object

In [ ]:
pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102915 entries, 0 to 102914
Data columns (total 2 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   text     102797 non-null  object
 1   summary  102915 non-null  object
dtypes: object(2)
memory usage: 1.6+ MB


In [ ]:
len(str(pre['text'].values).split()) #65 sum # 1504 text # max_text_len=100 max_summary_len=15

1504

In [ ]:
pre['text'][0]

"Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

In [ ]:
pre['summary'][0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

In [ ]:
pre['text'][1]

"Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more."

In [ ]:
pre['summary'][1]

'Delhi techie wins free food from Swiggy for one year on CRED'

In [ ]:
print(pre.shape)
print(pre.isnull().sum())

(102915, 2)
text       118
summary      0
dtype: int64


In [ ]:
pre_clean = pre.dropna().drop_duplicates()
#pre_clean['summary'] = pre['summary'].dropna().drop_duplicates()

In [ ]:
print(pre_clean.shape)
print(pre_clean.isnull().sum())

(102775, 2)
text       0
summary    0
dtype: int64


Shape of the Dataset without NULL values *(102775, 2)*

In [ ]:
def clean_text(text, remove_stopwords = True):
    '''Remove unwanted characters, stopwords, and format the text to create fewer nulls word embeddings'''

    # Convert words to lower case
    #text = text.lower()

    # Replace contractions with their longer forms
    if True:
        text = text.split()
        new_text = []
        for word in text:
            if word in contraction_mapping:
                new_text.append(contraction_mapping[word])
            else:
                new_text.append(word)
        text = " ".join(new_text)
    return text

In [ ]:
 contraction_mapping ={"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not",

                           "didn't": "did not", "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not",

                           "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",

                           "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would",

                           "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would",

                           "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam",

                           "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have",

                           "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock",

                           "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have",

                           "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is",

                           "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as",

                           "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would",

                           "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have",

                           "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have",

                           "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are",

                           "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",

                           "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is",

                           "where've": "where have", "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have",

                           "why's": "why is", "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have",

                           "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have", "y'all": "you all",

                           "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have",

                           "you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have",

                           "you're": "you are", "you've": "you have"}

In [ ]:
# Clean the summaries and texts
clean_summaries = []
for summary in pre_clean.summary:
    clean_summaries.append(clean_text(summary))
print("Summaries are complete.")

clean_texts = []
for text in pre_clean.text:
    clean_texts.append(clean_text(text))
print("Texts are complete.")

Summaries are complete.
Texts are complete.


In [ ]:
clean_summaries[0]

'upGrad learner switches to career in ML & Al with 90% salary hike'

In [ ]:
clean_texts[0]

"Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

# Cleaned Dataset Samples

In [ ]:
for i in range(5):
    print("Clean Review #",i+1)
    print(clean_summaries[i])
    print(clean_texts[i])
    print()


Clean Review # 1
upGrad learner switches to career in ML & Al with 90% salary hike
Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers.

Clean Review # 2
Delhi techie wins free food from Swiggy for one year on CRED
Kunal Shah's credit card bill payment platform, CRED, gave users a chance to win free food from Swiggy for one year. Pranav Kaushik, a Delhi techie, bagged this reward after spending 2000 CRED coins. Users get one CRED coin per rupee of bill paid, which can be used to avail rewards from brands like Ixigo, BookMyShow, UberEats, Cult.Fit and more.

Clean Review # 3
New Zealand end Rohit Sharma-led India's 12-match winning streak
New Zealand defeated India by 8

# Dividing into train and test samples

In [ ]:
idx = int(0.95*len(clean_texts))
print(len(clean_texts))
print(idx)
print(len(clean_texts)-idx)
train_texts = clean_texts[:idx]
test_texts = clean_texts[idx:]
train_sum = clean_summaries[:idx]
test_sum = clean_summaries[idx:]


102775
97636
5139


In [ ]:
!mkdir data_test
!mkdir data_train

# Formatting of Dataset into files

In [ ]:
for i, text in enumerate(train_texts):
    file_name = './data_train/data_train_'+ str(i)+'_review.story'
    with open(file_name,'w') as f:
        f.write(text+'\n\n@highlight\n\n'+train_sum[i])
    f.close()


In [ ]:
for i, text in enumerate(test_texts):
    file_name = './data_test/data_test_'+ str(i)+'_review.story'
    with open(file_name,'w') as f:
        f.write(text+'\n\n@highlight\n\n'+test_sum[i])
    f.close()

In [ ]:
!git clone https://github.com/ykumargupta/AbstractiveTextSummarizer.git
!mv AbstractiveTextSummarizer/* .
!rm -rf AbstractiveTextSummarizer
!wget http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip
!unzip stanford-corenlp-full-2018-02-27

Cloning into 'AbstractiveTextSummarizer'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 24 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (24/24), 2.06 MiB | 5.81 MiB/s, done.
Resolving deltas: 100% (6/6), done.
--2024-04-23 04:16:26--  http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip [following]
--2024-04-23 04:16:26--  https://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://downloads.cs.stanford.edu/nlp/so

In [ ]:
!export CLASSPATH=/content/stanford-corenlp-full-2018-02-27/stanford-corenlp-3.9.1.jar
!echo "Please tokenize this text." | java -cp stanford-corenlp-full-2018-02-27/stanford-corenlp-3.9.1.jar edu.stanford.nlp.process.PTBTokenizer

Please
tokenize
this
text
.
PTBTokenizer tokenized 5 tokens at 47.45 tokens per second.


In [ ]:
!mkdir output_data
!mkdir output_data/output_train
!mkdir output_data/output_test

# This step does these :-
1. Tokenizing the dataset files
2. Converting these tokenized files into encoded binary files
3. Chunking these files for better performance of pipeline

In [ ]:
!python make_datafiles_test.py  ./data_test  ./output_data/output_test

Streaming output truncated to the last 5000 lines.
./output_data/output_test/tokenized_stories_dir/data_test_1657_review.story
./output_data/output_test/tokenized_stories_dir/data_test_1502_review.story
./output_data/output_test/tokenized_stories_dir/data_test_664_review.story
./output_data/output_test/tokenized_stories_dir/data_test_3974_review.story
./output_data/output_test/tokenized_stories_dir/data_test_749_review.story
./output_data/output_test/tokenized_stories_dir/data_test_2773_review.story
./output_data/output_test/tokenized_stories_dir/data_test_4051_review.story
./output_data/output_test/tokenized_stories_dir/data_test_1491_review.story
./output_data/output_test/tokenized_stories_dir/data_test_1915_review.story
./output_data/output_test/tokenized_stories_dir/data_test_3248_review.story
./output_data/output_test/tokenized_stories_dir/data_test_1931_review.story
./output_data/output_test/tokenized_stories_dir/data_test_3943_review.story
./output_data/output_test/tokenized_sto

In [ ]:
!python make_datafiles_train.py  ./data_train  ./output_data/output_train/

Streaming output truncated to the last 5000 lines.
./output_data/output_train/tokenized_stories_dir/data_train_63902_review.story
./output_data/output_train/tokenized_stories_dir/data_train_77068_review.story
./output_data/output_train/tokenized_stories_dir/data_train_10703_review.story
./output_data/output_train/tokenized_stories_dir/data_train_72285_review.story
./output_data/output_train/tokenized_stories_dir/data_train_14452_review.story
./output_data/output_train/tokenized_stories_dir/data_train_41403_review.story
./output_data/output_train/tokenized_stories_dir/data_train_76902_review.story
./output_data/output_train/tokenized_stories_dir/data_train_2794_review.story
./output_data/output_train/tokenized_stories_dir/data_train_82786_review.story
./output_data/output_train/tokenized_stories_dir/data_train_77503_review.story
./output_data/output_train/tokenized_stories_dir/data_train_76513_review.story
./output_data/output_train/tokenized_stories_dir/data_train_36604_review.story
./

Package to download files from Google Drive

In [ ]:
!git clone https://github.com/GitHub30/gdrive.sh.git

Cloning into 'gdrive.sh'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 89 (delta 2), reused 0 (delta 0), pack-reused 83
Receiving objects: 100% (89/89), 20.29 KiB | 20.29 MiB/s, done.
Resolving deltas: 100% (47/47), done.


In [ ]:
!curl gdrive.sh | bash -s https://drive.google.com/file/d/1EGtpV1ZQP8_vGCtL16k3i0qVNOBcmp7F/view?usp=sharing
!unzip logroot.zip
!mv /content/content/logroot /content/
!rm -rf /content/content/

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: gdrive.sh
unzip:  cannot find or open logroot.zip, logroot.zip.zip or logroot.zip.ZIP.
mv: cannot stat '/content/content/logroot': No such file or directory


In [ ]:
%tensorflow_version

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
!mkdir finished_files
!cp -r /content/output_data/output_train/finished_files/* /content/finished_files/
!cp -r /content/output_data/output_test/finished_files/* /content/finished_files/

# Setup PyRouge to estimate ROUGE scores

In [ ]:
!git clone https://github.com/bheinzerling/pyrouge
%cd pyrouge
!python setup.py install
!pip install -e .
!sudo apt install libxml-parser-perl


Cloning into 'pyrouge'...
remote: Enumerating objects: 551, done.
remote: Total 551 (delta 0), reused 0 (delta 0), pack-reused 551
Receiving objects: 100% (551/551), 123.17 KiB | 700.00 KiB/s, done.
Resolving deltas: 100% (198/198), done.
/content/pyrouge
running install
running bdist_egg
running egg_info
creating pyrouge.egg-info
writing pyrouge.egg-info/PKG-INFO
writing dependency_links to pyrouge.egg-info/dependency_links.txt
writing top-level names to pyrouge.egg-info/top_level.txt
writing manifest file 'pyrouge.egg-info/SOURCES.txt'
writing manifest file 'pyrouge.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pyrouge
copying pyrouge/test.py -> build/lib/pyrouge
copying pyrouge/Rouge155.py -> build/lib/pyrouge
copying pyrouge/__init__.py -> build/lib/pyrouge
creating build/lib/pyrouge/utils
copying pyrouge/utils/log.py -> build/lib/pyrouge/utils
copying pyrouge/u

In [ ]:
!pwd

/content/pyrouge


In [ ]:
%cd ..

/content


In [ ]:
#git clone https://github.com/andersjo/pyrouge
!tar -xvf /content/ROUGE-1.5.5.tar.gz
!pyrouge_set_rouge_path /content/ROUGE-1.5.5
!python -m pyrouge.test

ROUGE-1.5.5/
ROUGE-1.5.5/runROUGE-test.pl
ROUGE-1.5.5/XML/
ROUGE-1.5.5/XML/DOM/
ROUGE-1.5.5/XML/DOM/DocumentType.pod
ROUGE-1.5.5/XML/DOM/AttDef.pod
ROUGE-1.5.5/XML/DOM/Document.pod
ROUGE-1.5.5/XML/DOM/DocumentFragment.pod
ROUGE-1.5.5/XML/DOM/CharacterData.pod
ROUGE-1.5.5/XML/DOM/DOMException.pm
ROUGE-1.5.5/XML/DOM/Notation.pod
ROUGE-1.5.5/XML/DOM/ElementDecl.pod
ROUGE-1.5.5/XML/DOM/Element.pod
ROUGE-1.5.5/XML/DOM/Attr.pod
ROUGE-1.5.5/XML/DOM/NodeList.pm
ROUGE-1.5.5/XML/DOM/NodeList.pod
ROUGE-1.5.5/XML/DOM/PerlSAX.pm
ROUGE-1.5.5/XML/DOM/Node.pod
ROUGE-1.5.5/XML/DOM/EntityReference.pod
ROUGE-1.5.5/XML/DOM/CDATASection.pod
ROUGE-1.5.5/XML/DOM/XMLDecl.pod
ROUGE-1.5.5/XML/DOM/NamedNodeMap.pod
ROUGE-1.5.5/XML/DOM/AttlistDecl.pod
ROUGE-1.5.5/XML/DOM/ProcessingInstruction.pod
ROUGE-1.5.5/XML/DOM/NamedNodeMap.pm
ROUGE-1.5.5/XML/DOM/Parser.pod
ROUGE-1.5.5/XML/DOM/Comment.pod
ROUGE-1.5.5/XML/DOM/DOMImplementation.pod
ROUGE-1.5.5/XML/DOM/Entity.pod
ROUGE-1.5.5/XML/DOM/Text.pod
ROUGE-1.5.5/XML/DOM.

Input Parameters for Summarization Model are :-
1. Mode of Processing - train
2. Chunked Train Files
3. Vocabulary generated using tokenizing training files
4. Trained checkpoints
5. Encoding , Decoding Steps limit
6. Enable coverage Mechanism or not

In [ ]:
!python run_summarization.py --mode=train --data_path=/content/finished_files/chunked/train_* --vocab_path=/content/finished_files/vocab --log_root=/content/logroot/ --exp_name=pretrained_model --max_enc_steps=100 --max_dec_steps=15 --coverage=1 #--restore_best_model=1



W0804 03:49:01.884801 140087188129664 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.


W0804 03:49:01.884986 140087188129664 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.


W0804 03:49:01.885111 140087188129664 module_wrapper.py:139] From run_summarization.py:272: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Starting seq2seq_attention in train mode...
I0804 03:49:01.885228 140087188129664 run_summarization.py:272] Starting seq2seq_attention in train mode...
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: 111-year-old

W0804 03:49:02.242486 140087188129664 module_wrapper.py:139] From run_summarization.py:305: The name t

Evaluation Mode checks for the best train estimated model having low total loss, seq2seq2 and coverage loss

In [ ]:
!python run_summarization.py --mode=eval --data_path=/content/finished_files/chunked/test_* --vocab_path=/content/finished_files/vocab --log_root=/content/logroot/ --exp_name=pretrained_model --max_enc_steps=100 --max_dec_steps=15 --coverage=1



W0804 03:49:56.782798 140618406229888 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.


W0804 03:49:56.782992 140618406229888 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.


W0804 03:49:56.783119 140618406229888 module_wrapper.py:139] From run_summarization.py:272: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Starting seq2seq_attention in eval mode...
I0804 03:49:56.783226 140618406229888 run_summarization.py:272] Starting seq2seq_attention in eval mode...
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: 111-year-old

W0804 03:49:57.728818 140618406229888 module_wrapper.py:139] From run_summarization.py:305: The name tf.

# Generate Samples from our trained model

In [ ]:
!python run_summarization.py --mode=decode --data_path=/content/finished_files/chunked/test_* --vocab_path=/content/finished_files/vocab --log_root=/content/logroot/ --exp_name=pretrained_model --max_enc_steps=100 --max_dec_steps=15 --coverage=1



W0804 03:50:28.242059 139865190901632 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.


W0804 03:50:28.242273 139865190901632 module_wrapper.py:139] From run_summarization.py:271: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.


W0804 03:50:28.242419 139865190901632 module_wrapper.py:139] From run_summarization.py:272: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Starting seq2seq_attention in decode mode...
I0804 03:50:28.242512 139865190901632 run_summarization.py:272] Starting seq2seq_attention in decode mode...
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: 111-year-old

W0804 03:50:28.394093 139865190901632 module_wrapper.py:139] From run_summarization.py:305: The name

# Calculate ROUGE scores on Test Dataset
Parameter- using single_pass

In [ ]:
!python run_summarization.py --mode=decode --data_path=/content/finished_files/chunked/test_* --vocab_path=/content/finished_files/vocab --log_root=/content/logroot/ --exp_name=pretrained_model --max_enc_steps=100 --max_dec_steps=15 --coverage=1 --single_pass=1

In [ ]:
with open('/content/logroot/pretrained_model/decode_test_100maxenc_4beam_35mindec_15maxdec_ckpt-263534/ROUGE_results.txt', "r") as file1:
    FileContent = file1.read()
    print(FileContent)


ROUGE-1:
rouge_1_f_score: 0.4511 with confidence interval (0.4460, 0.4567)
rouge_1_recall: 0.5412 with confidence interval (0.5350, 0.5476)
rouge_1_precision: 0.3945 with confidence interval (0.3897, 0.3997)

ROUGE-2:
rouge_2_f_score: 0.2415 with confidence interval (0.2359, 0.2471)
rouge_2_recall: 0.2951 with confidence interval (0.2883, 0.3019)
rouge_2_precision: 0.2093 with confidence interval (0.2044, 0.2143)

ROUGE-l:
rouge_l_f_score: 0.4135 with confidence interval (0.4082, 0.4192)
rouge_l_recall: 0.4959 with confidence interval (0.4895, 0.5024)
rouge_l_precision: 0.3616 with confidence interval (0.3568, 0.3666)

